### ISSUE TITLE
Use icon instead of number in step

### ISSUE THREAD

**Issue by abarazal** [ernestoyaquello/VerticalStepperForm#101]
Is it possible to use an icon instead of a number in step indicator bubble?

**Comment by ernestoyaquello** [comment]
I am afraid I don't want to make the implementation of this library more complex with such a niche feature.

However, you can implement this yourself. Find the view with the ID `step_number_circle` and put an `ImageView` with your icon in there, on top of everything else. It's a little bit hacky, but it should do the trick.

I hope that helps!
