### ISSUE TITLE
Can we dynamicaly change the view in a step depending o the previous step

### ISSUE THREAD

**Issue by ripleyXLR8** [ernestoyaquello/VerticalStepperForm#29]
Hi,

Thank you for your work on the library ;-)

I would like to know if there is any to dynamicaly change the view content of a step to make it reflect answer of the previous steps?

Best regards

Richard

**Comment by ripleyXLR8** [comment]
Answering myself.

I did not find a a way to replace the view inside the step so i created a layout containing the different view i want and i pass this layout to the step. Then I set the visibility of the view inside this layout.

If you think of something cleaner.... do not hesitate.

**Comment by ernestoyaquello** [comment]
Closing this issue because you already answered yourself a long time ago.
