### ISSUE TITLE
How to control textsize of steps, if the length of step text is long, the step title gets cutoff.

### ISSUE THREAD

**Issue by Frankenstein666** [ernestoyaquello/VerticalStepperForm#31]

**Comment by alouanemed** [comment]
Can you provide a screenshot ?

**Comment by Frankenstein666** [comment]
![screenshot_20160829-211208_20160829211737937_20160829211947471](https://cloud.githubusercontent.com/assets/11345511/18057200/b37b8256-6e2e-11e6-930a-5972720927d4.jpg

**Comment by ahmadalibaloch** [comment]
Same problem here. Any solution on way or I needa make the change source code?

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, this is no longer a problem in the new version of the library, please go check it out if you are still interested!
