### ISSUE TITLE
Remove Attribute application@allowBackup value

### ISSUE THREAD

**Issue by diyfr** [ernestoyaquello/VerticalStepperForm#32]
It's for an application not a library ?

``` log
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:16:9-36
    is also present at [com.ernestoyaquello.stepperform:vertical-stepper-form:0.9.9] AndroidManifest.xml:12:9-35 value=(true).
``
```

**Comment by anthonygraignic** [comment]
Hi, I add the same problem and had to for the merge using `tools:replace=""` attribute (more info from [Android-dev](https://developer.android.com/studio/build/manifest-merge.html) ).
I submitted the PR #28 which fix the problem, so you should wait for a new release :).

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding this issue, this is no longer a problem in the new version of the library.
