### ISSUE TITLE
Is it possible to add a custom font method?

### ISSUE THREAD

**Issue by joseacisneros** [ernestoyaquello/VerticalStepperForm#33]
Hi Ernesto,

Thank you so much for this library! 

Do you think if is possible to add a method that let change the font type (custom font) to the Titles and Sub titles?

Thanks again for this library, it has help me a lot.

**Comment by velval** [comment]
For someone getting here the answer is yes you can. Have a look at this method under the VerticalStepperFormLayout.

```
protected LinearLayout generateStepLayout() {
        LayoutInflater inflater = LayoutInflater.from(context);
        return (LinearLayout) inflater.inflate(R.layout.step_layout, content, false);
    }
```

All you need to do is to copy and modify the **R.layout.step_layout**  layout as you needed for your project.

**Comment by ernestoyaquello** [comment]
I see this was already resolved, so I will close the issue. Please be aware that I have just refactored the library and the referenced code might not be present on it anymore.
