### ISSUE TITLE
Is it possible to add a hook to the buttons

### ISSUE THREAD

**Issue by arvikachristy** [ernestoyaquello/VerticalStepperForm#34]
Is it possible to add a hook to the buttons so I can do other stuff such as communicating the info back to the API? 

(In my case I need access to each button and after confirmation button as well)

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, in the new version of the library this can be achieved by listening to the callbacks `onStepOpened()`, `onStepClosed()`, `onStepMarkedAsCompleted()` and `onStepMarkedAsUncompleted()`. If that weren't enough, now the form can be configured to not show its default buttons, so you could replace them with your own and handle clicks and everything yourself.
