### ISSUE TITLE
Decrease to api level 14

### ISSUE THREAD

**Issue by g0ddest** [ernestoyaquello/VerticalStepperForm#36]
Is it possible?

**Comment by g0ddest** [comment]
I see that the only problem is setBackground.
Maybe you can use setBackgroundResource in lower api instead?

**Comment by parveenkumardeeva** [comment]
Kindly merge  WonderCsabo commit and release a new version which supports at least API level 15

**Comment by WonderCsabo** [comment]
@parveenkumardeeva i cannot do it, because i do not own the repo, @ernestoyaquello does.

**Comment by ernestoyaquello** [comment]
I will close this issue because it doesn't really makes sense anymore. The new version of the library has a minimum of SDK of 19, which is currently enough to support [96.5% of all devices](https://developer.android.com/about/dashboards/).
