### ISSUE TITLE
Navigation To Any Step

### ISSUE THREAD

**Issue by vikasdubeyyy** [ernestoyaquello/VerticalStepperForm#40]
How can we navigate to any step i.e. independent from other.
If there is 5 steps, so how can I jump direct to step 3 from step 1 without navigating step 2.

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, this functionality is now implemented in the new version of the library, so please go check it out if you are still interested.
