### ISSUE TITLE
Change "Confirm data" text

### ISSUE THREAD

**Issue by Stjerndal** [ernestoyaquello/VerticalStepperForm#41]
Is it possible to change the text of the final, automatically added, step "Confirmation" and it's corresponding button? Without downloading the source that is. I could not find a way, and it's a quite vital function, especially if the app is in another language.

**Comment by Orhan118** [comment]
I also could not find how to change the text "Countinue" button

**Comment by Stjerndal** [comment]
Yeah, I did try that. This does however change the value of that button (or whatever) for **all** of the apps forms. Each time I create a new form I would like to specify e.g. the "Confirmation" text for that particular form, in run time.

For example, in one form I would like to have "Create account" as the confirmation button, but in another one I would like to have "Confirm purchase".

**Comment by vpratfr** [comment]
Same question here. Library looks very promising, but there are a few things to adjust.

**Comment by cutiko** [comment]
Create your own class then customized text there:

```
public class CustomStepper extends VerticalStepperFormLayout {

    //Don't forget constructors, rule of thumb is for xml 2 params for java 1 param

    protected void setUpStepLayoutAsConfirmationStepLayout(LinearLayout stepLayout) {
           super.setUpStepLayoutAsConfirmationStepLayout(stepLayout);
           //If you look at the original class this is the button, is protected so you can use it
           //You can use it after the super, it is instantiated in there
          confirmationButton.setText("SOMETHING")
    }
}
```

Creating views in this manner it is something really handy, now you can create one for each different form. Please remember to use it the XML and also in the builder.

**Comment by hardysim** [comment]
Hmm, this would be a way to to it but I'd like it better when there is a setter for the text so I don't need to create new classes each time I want to change the name.

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, the option to change the text of the button of the last step is now implemented in the new version of the library, so please go check it out if you are still interested.
