### ISSUE TITLE
Why is activity_horizontal_margin set for w820dp-v13?

### ISSUE THREAD

**Issue by seasox** [ernestoyaquello/VerticalStepperForm#43]
I figured that activity_horizontal_margin is set to 64dp for w820dp-v13, which killed my layout. I had to override it in my own values-w820dp-v13. Why is this set?

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, I don't really know why this was there, but after a big refactoring this dimensions are no longer in the library.
