### ISSUE TITLE
Add method getView(stepNumber) to access children inputs' data - to set that step number status

### ISSUE THREAD

**Issue by ahmadalibaloch** [ernestoyaquello/VerticalStepperForm#44]
I have a form, dynamically created, at each stepNumber, of which the fields are required or not depending on data. On each `EditText` I need all the form's EditTexts to check if all required fields are filled or not, the result of which will set a `step`'s complete status.

At the moment, on creating views for steps, I am also saving `Views` in `HashMap` against `stepNumber`, so I can access all the views when any field in that `stepNumber` is edited.

The method could be called `getView(stepNumber)` or `getForm(stepNumber)`

**Comment by Dule95D** [comment]
Inside `VeticalStepperFormLayout.java` insert this method:
`public View getActiveStepView() {
        return stepLayouts.get(activeStep).findViewById(R.id.step_content);
    }`

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, I have refactored the whole library and this is now possible in the new version, so please go check it out in the case you are still interested.
