### ISSUE TITLE
Can we enter dynamic fields?

### ISSUE THREAD

**Issue by SilverFoxA** [ernestoyaquello/VerticalStepperForm#48]
As of now the fields seems bit hardcoded, thus is it possible to make dynamic fields creation?

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, I am not sure I follow you. If your request is to be able to add or remove steps on a form that has already been created and rendered, that is still not possible, and it is not something that I have in the current roadmap of the library for the moment.

I will close the issue for now, but I might come back to this in the future if I ever decide to implement this feature. Needless to say, feel free to implement it yourself and create a PR if you feel like doing it!
