### ISSUE TITLE
Make stepContentView match parent width in stepContent

### ISSUE THREAD

**Issue by Benjoyo** [ernestoyaquello/VerticalStepperForm#51]
First, thanks for making everything protected and putting things in fine grained methods so it's very easy to extend and alter the behavior of this library.

I'm not sure if this is a bug or just an improvement, but I think that the individual stepContentViews should be just the width of their parent stepContent and not wrap it's contents which is the standard behavior with addView(). This way you run into trouble if you want to make full width components inside a stepContentView without using actual dp values.

I suggest changing setUpStep(int stepNumber) to:
```java
protected void setUpStep(int stepNumber) {
        LinearLayout stepLayout = createStepLayout(stepNumber);
        if (stepNumber < numberOfSteps) {
            // The content of the step is the corresponding custom view previously created
            RelativeLayout stepContent = (RelativeLayout) stepLayout.findViewById(R.id.step_content);
            // start new
            RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT); 
            stepContent.addView(stepContentViews.get(stepNumber), params);
            // end new
        } else {
            setUpStepLayoutAsConfirmationStepLayout(stepLayout);
        }
        addStepToContent(stepLayout);
}
```

**Comment by nlasso** [comment]
I have the same issue. Must use a full width of the step container.

**Comment by kr05** [comment]
@Benjoyo you mentioned the library is very easy to extend and modify, but unfortunately that has not been my experience. I attribute this to my shallow knowledge of java, but how do I implement your changes? 

I tried creating my own class CustomVerticaStepperFormLayout, which extends VerticalStepperFormLayout, and overrided the setUpStep method. Unfortunately, the new method is not being called. The code for CustomVerticalStepperFormLayout is in this [codeshare](https://codeshare.io/aY7Lbm). 

Within my code, I'm calling the builder method as follows:

       //This is a reference to the stepper widget inside my view.
        VerticalStepperFormLayout verticalStepperForm = findViewById(R.id.activate_tickets_stepper);

        // Setting up and initializing the form
        //mySteps: array of strings that represents title for steps
        CustomVerticalStepperFormLayout.Builder.newInstance(verticalStepperForm, mySteps, this, this)
                .showVerticalLineWhenStepsAreCollapsed(true)
                .materialDesignInDisabledSteps(true)
                .primaryColor(accentColor)
                .primaryDarkColor(primaryColor)
                .stepTitleTextColor(primaryColor)
                .displayBottomNavigation(false)
                .buttonPressedTextColor(accentColor)
                .init();

Any help would be greatly appreciated!

**Comment by kr05** [comment]
I finally figured out the problem! For those of you with the same issue, I simply replaced my widget with:

<com.example.testuser.testproject.CustomVerticalStepperFormLayout
        android:id="@+id/activate_tickets_stepper"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentTop="true" />

and replaced the VerticalStepperFormLayout object with CustomVerticalStepperFormLayout.

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, this is now implemented in the new version of the library, so please go check it out if you are still interested.
