### ISSUE TITLE
Button "Continue" enabled by default

### ISSUE THREAD

**Issue by RoRoche** [ernestoyaquello/VerticalStepperForm#52]
When opening a step, the "Continue" button is enabled by default.
It should be enabled only when the step is completed, no?

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, the Continue button is and has always been disabled by default; you have to mark the step as completed to activate it.
