### ISSUE TITLE
Error: Error:No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.

### ISSUE THREAD

**Issue by sgatibaru** [ernestoyaquello/VerticalStepperForm#53]
i love your form and i would like to use it for my project. However, when i build load it anf gradle builds, i get the error message:

`Error:No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.`

Kindy assist me in fixing this error.

Regards.

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, I have refactored the whole library and this should not happen anymore. Please go check out the new version in case you are still interested.
