### ISSUE TITLE
Disable confirmation step

### ISSUE THREAD

**Issue by silviahisham** [ernestoyaquello/VerticalStepperForm#59]
Can you please add an option to disable the confirmation step.

**Comment by kr05** [comment]
I also needed the option to disable the confirmation step; unfortunately, it seems like there hasn't been any recent activity. What I ended up doing is going through the pull request made by the awesome eoinsha [here](https://github.com/ernestoyaquello/vertical-stepper-form/pull/57). After a couple of hours of fixing errors, I was able to integrate the changes into my code.

**Comment by silviahisham** [comment]
yes, I ended up doing the same

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, the ability to not include the confirmation step is now implemented in the new version of the library, so please go check it out if you are still interested.
