### ISSUE TITLE
Steps do not support match_parent height

### ISSUE THREAD

**Issue by NewColours** [ernestoyaquello/VerticalStepperForm#64]
If the layout for an individual step uses the height 'match_parent', views will expand for ever and navigating back to a step will open it extremely slowly. Seen on Pixel 2 (Oreo)

Current work around is to use a fixed height or wrap_content.

Perhaps the library should automatically change match_parent to wrap_content where required, because users who haven't looked at the source may not be able to find the cause

**Comment by ernestoyaquello** [comment]
First of all, sorry for the immense delay in my response; after a long period of abandonment it is only recently that I have found the time to work on this library again.

Regarding the issue, I think this is to be expected. For instance, a `RecyclerView` will also display its items gigantic when you set their height as `match_parent`. Thus, I don't really think I should take care of the height of the step content provided by the user within the library; it is the user's responsibility to avoid using a `match_parent` height in the layout of their steps.
