### ISSUE TITLE
Stepper state not restored in fragments

### ISSUE THREAD

**Issue by DhruvamSharma** [ernestoyaquello/VerticalStepperForm#69]
When I rotate the device, the stepper state is not restored. 
I used this code:

`@Override
    public void onSaveInstanceState(@NonNull Bundle outState) {

        //store the state of the stepper for screen rotations

        Parcelable parcelable = verticalStepperForm.onSaveInstanceState();

        //Parcelable stateOfStepper = verticalStepperForm.onSaveInstanceState();

        outState.putParcelable(STEPPER_STATE, parcelable);

        super.onSaveInstanceState(outState);

    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {

        if( savedInstanceState != null &&savedInstanceState.containsKey(STEPPER_STATE)) {

            Parcelable parcelable = savedInstanceState.getParcelable(STEPPER_STATE);

            //verticalStepperForm.goToStep(stateOfStepper, false);

            //onStepOpening(stateOfStepper);

            verticalStepperForm.onRestoreInstanceState(parcelable);

        }

        super.onActivityCreated(savedInstanceState);

    }

`

**Comment by ernestoyaquello** [comment]
I can see some weird things in your code, but I am not sure why this was happening. In any case, I have recently refactored the whole library and I have personally tested that the restoration works. If you are still interested, please check out the new version of the library and follow the instructions included in the readme file to make the form work and restore correctly.
