### ISSUE TITLE
Should the library handle enter events?

### ISSUE THREAD

**Issue by MuriloCalegari** [ernestoyaquello/VerticalStepperForm#76]
It would be nice if the user could go to the next step if they press the enter button on their keyboard.

**Comment by ernestoyaquello** [comment]
This is not for the library to do, bur for the developer. If you are the one who adds an `EditText` to the step that will cause the keyboard to show up, then you are the one responsible for handling the interactions that the user has with it.

As an example of how to do it, please take a look at [the sample app](https://github.com/ernestoyaquello/VerticalStepperForm/tree/master/app), as it actually handles "enter" events.
