### ISSUE TITLE
text field

### ISSUE THREAD

**Issue by sina202098** [ernestoyaquello/VerticalStepperForm#77]
the text field doesn't support other languages like Rtl languages and how can I adjust the stages in right side of the screen
thanks a lot

**Comment by ernestoyaquello** [comment]
The support for right-to-left languages is handled by the system, so I don't really know what you are asking for. This library is already using `start` and `end` instead of `left` and `right` in all its XML attributes, which means that the form does get mirrored when your device is set up with a RTL language.

On the other hand, the text field is not even part of the library, but a component that the developer has to implement as the content of the step. Therefore, it is up to you to configure it as you wish.

I hope this can be of help.

**Comment by sina202098** [comment]
Hello my friend;
first of all I 'd like to express my deepest thanks for your urgent and kind response
let me to explain my problem about this code I want to arrange this code so that I put the component in right of the window as I show you in attached picture in below  .  as you see I edit this code as I show you in blue selected color I did it and that's ok for vertical circles but I couldn't change the vertical line that placed in left side to the right as I did for  stepper _ circles , How can I edit this code so that bring the left vertical line form left to right side of the window as I did for circles.  thanks a lot my friend
[cid:657d1a72-bf28-4100-b2e6-dc10e4c6865d]

**Comment by sina202098** [comment]
Hello my friend;

first of all I 'd like to express my deepest thanks for your urgent and kind response
let me to explain my problem about this code I want to arrange this code so that I put the component in right of the window as I show you in attached picture in below  .  as you see I edit this code as I show you in blue selected color I did it and that's ok for vertical circles but I couldn't change the vertical line that placed in left side to the right as I did for  stepper _ circles , How can I edit this code so that bring the left vertical line form left to right side of the window as I did for circles.  thanks a lot my friend.
http://uupload.ir/files/jzb1_screenshot_(21).png

**Comment by ernestoyaquello** [comment]
If you set your device to an RTL language (for example, Arabic), the whole form will be mirrored automatically, just as you want. However, if you want to mirror the layout manually yourself for any language, then I am afraid you will have to figure out how to do it on your own.

On the other hand, I can see that there is a `RelativeLayout` in your screenshot, so you must be using an old version of this library (there aren't any relative layouts in the new one). I encourage you to use the latest version, which is better than the old one in many ways.
