### ISSUE TITLE
Allow customization of "right-part" startMargin

### ISSUE THREAD

**Issue by Judas** [ernestoyaquello/VerticalStepperForm#78]
Hello,

I'm a bit of a pixel-alignment annoying person so I'd like to align the right part of the stepper to the Toolbar title like here : https://gist.github.com/Judas/073e84395fb2a3607a0c5c3c781fe8b1
Could it be possible to make this customizable ?

The start margin is hardcoded to 16dp ([here](https://github.com/ernestoyaquello/VerticalStepperForm/blob/master/vertical-stepper-form/src/main/res/layout/step_layout.xml#L68) & [here](https://github.com/ernestoyaquello/VerticalStepperForm/blob/master/vertical-stepper-form/src/main/res/layout/step_layout.xml#L141)) so for now here is what I need to do to achieve it :

```java
private void addStepperMargin(final int marginPx) {
    LinearLayout formContainer = (LinearLayout) stepper.getChildAt(0);
    ScrollView formScroll = (ScrollView) formContainer.getChildAt(0);
    LinearLayout formRoot = (LinearLayout) formScroll.getChildAt(0);

    for (int index = 0; index < formRoot.getChildCount(); index++) {
        LinearLayout stepLayout = (LinearLayout) formRoot.getChildAt(index);
        LinearLayout stepHeader = (LinearLayout) stepLayout.getChildAt(0);
        LinearLayout stepHeaderContent = (LinearLayout) stepHeader.getChildAt(1);
        LinearLayout.LayoutParams headerContentParams = (LinearLayout.LayoutParams) stepHeaderContent.getLayoutParams();
        headerContentParams.setMarginStart(marginPx);
        stepHeaderContent.setLayoutParams(headerContentParams);

        LinearLayout stepContent = (LinearLayout) stepLayout.getChildAt(1);
        LinearLayout stepContentContent = (LinearLayout) stepContent.getChildAt(1);
        LinearLayout.LayoutParams contentContentParams = (LinearLayout.LayoutParams) stepContentContent.getLayoutParams();
        contentContentParams.setMarginStart(marginPx);
        stepContentContent.setLayoutParams(contentContentParams);
    }
}
```

Thank you!

**Comment by ernestoyaquello** [comment]
Since you have already implemented a solution for the issue, would you mind creating a PR with it? If you don't have the time or just don't want to, then I will add this in in the weekend when I have some time. Cheers!

**Comment by ernestoyaquello** [comment]
@Judas Just in case you are still interested, I have updated the library so this margin can be customised.

In XML:

```xml
<ernestoyaquello.com.verticalstepperform.VerticalStepperFormView
    app:form_horizontal_margin_from_step_numbers_to_content="16dp"
    ... />
```

In code:

```java
verticalStepperForm
    .setup(this, exampleStep1, exampleStep2, exampleStep3)
    .marginFromStepNumbersToContentInPx(48)
    ...
    .init();
```

I hope this helps!
