### ISSUE TITLE
Step title as icon

### ISSUE THREAD

**Issue by Gkundu1** [ernestoyaquello/VerticalStepperForm#79]
Is it possible to add icon/drawable to the step instead for using the title as String?

**Comment by ernestoyaquello** [comment]
Not currently, but I can consider adding this feature if it makes sense. Could you please provide a use case for it? I cannot really think of one.

**Comment by Gkundu1** [comment]
Hi ernestoyaquello, thanks for the reply. Here is the use case 
Right now the library support only String i.e `Step<String>` . So if it possible to have class like `Step<Drawable>` so that while initializing the step we can pass either text or drawable for each step.

**Comment by ernestoyaquello** [comment]
Hi again. I wasn't asking about the implementation, but about the cases in which this feature could be necessary and/or useful. I just don't want to overcomplicate the library with new functionalities that aren't really valuable or don't make sense.

**Comment by Gkundu1** [comment]
It as the requirement of the project which has two different step icon which we need to change while we move forward to next step i.e initially active step icon and later on step change inactive step icon.

**Comment by ernestoyaquello** [comment]
I think that what you are asking for would definitely over-complicate the library, as it is not a standard feature that most people would need, but just a very specific requirement of your project.

However, I have updated the library to include a method that you can extend to define your own step layout, which could be used to achieve what you are trying to do. Please [take a look](https://github.com/ernestoyaquello/VerticalStepperForm/pull/80/commits/a09fef965348aea81292f908d3e92eda33228fff).
