### ISSUE TITLE
ListView only shows one element

### ISSUE THREAD

**Issue by equilDev** [ernestoyaquello/VerticalStepperForm#81]
Hey,

i tried to put a ListView in one step, but it only shows one element. Isn't it possible to show multiple lines in one step ?

LG
Lukas

**Comment by ernestoyaquello** [comment]
Hi! I am sorry, but I cannot reproduce your issue. I am playing around with the sample app and I am able to see an entire list when I add it into a step:

![photo_2019-06-23_11-37-47](https://user-images.githubusercontent.com/2463287/59975044-8c75fe00-95ab-11e9-8484-e6260aa4b1ce.jpg)

Could you please show me your code? Thanks!

**Comment by equilDev** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <ListView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/listview" />
</RelativeLayout>
```


```
       LayoutInflater inflater = LayoutInflater.from(getContext());
        View aysStepContent = inflater.inflate(R.layout.trainingslist, null, false);

        ListView userNameView = aysStepContent.findViewById(R.id.listview);



        String[] val = new String[]{
                "Nackensprenger",
                "Fliegende Frosch"
        };
        userNameView.setAdapter(new ArrayAdapter<String>(getContext(),android.R.layout.simple_list_item_1,val));
        userNameView.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {

            }
        });
```

![Screenshot_20190623-134509](https://user-images.githubusercontent.com/34444045/59975890-dd8eed80-95bd-11e9-980e-fa09ad920cc3.png)

**Comment by equilDev** [comment]
When I tap to the "Nackensprenger" element it show me a scrollbar. But i think all scrolling events are handled by the verticalstepper.

**Comment by ernestoyaquello** [comment]
Turns out it works with a `RecyclerView`, but fails with a `ListView`. Please switch to a `RecyclerView` and tell me how it goes!

**Comment by equilDev** [comment]
Yes, RecyclerView does work well. Thank you very much for your help
