### ISSUE TITLE
ViewTreeObserver.OnGlobalLayoutListener leaks memory.

### ISSUE THREAD

**Issue by DeweyReed** [ernestoyaquello/VerticalStepperForm#82]
LeakCanary told me this.

After exploring the code, I find that when VerticalStepperForm is used in the fragment, added OnGlobalLayoutListener (https://github.com/ernestoyaquello/VerticalStepperForm/blob/master/vertical-stepper-form/src/main/java/ernestoyaquello/com/verticalstepperform/VerticalStepperFormView.java#L769) doesn't get removed when the fragment is detached so the view can't be collected by GC.

Using this view in an activity is fine because the root view will be destroyed with the activity.

**Comment by ernestoyaquello** [comment]
This should hopefully be fixed in the version 2.2.1. Thanks for taking the time to report the issue!
