### ISSUE TITLE
Close the last step on complete

### ISSUE THREAD

**Issue by VladimirMi** [ernestoyaquello/VerticalStepperForm#87]
Hi, thanks for the useful library.
Can you add an option to close the last step after completing the form, instead of disabling the next button?

**Comment by ernestoyaquello** [comment]
Hi, and sorry for the delay in my answer.

I have implemented this feature, please check out the version 2.2.3 of the library. You can enable it doing:

```xml

<ernestoyaquello.com.verticalstepperform.VerticalStepperFormView
    ...
    app:form_close_last_step_on_completion="true" />
```

Many thanks for your suggestion!
