### ISSUE TITLE
Slow in opening with non-fixed height RecyclerView

### ISSUE THREAD

**Issue by renyuneyun** [ernestoyaquello/VerticalStepperForm#88]
When opening a Step which inflates a `RecyclerView`, the opening process is extremely slow. The length of the Form extends slowly and the color turns from white to colorful really slow. In the end, it will be loaded and the height is normal (I remember, because I only fully waited for once).

During testing, I discovered that if the `RecyclerView` has a **fixed** height (e.g. `400dp`), this problem does not appear at all. As long as the `RecyclerView` has `android:height=match_parent` or `wrap_content`, the problem appears.

I read #64, but it only mentions using `match_parent` but not `wrap_content`, and it does not mention the **slow** problem at all.

**Comment by ernestoyaquello** [comment]
To work properly, the animations need to know the expected height of a view beforehand, but getting this height can be tricky when the view to animate is a recyclerview. I will try to reproduce the issue and look for a solution when I have time. Thanks for reporting it!

**Comment by ernestoyaquello** [comment]
Hi again, and sorry about the delay.

I tried a few things, but none of them seemed to work properly, so I am afraid that the only solution is to set a fixed height. Have you tried setting `setHasFixedSize()` on your recyclerview to see if that helps?

**Comment by ernestoyaquello** [comment]
Given there hasn't been activity in more than a month, I will close the issue.
