### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by kostadin24** [ernestoyaquello/VerticalStepperForm#90]
Hello,
If I have multiple steps screen become scrollable.
Use can easy scroll content and current active step become hidden.

Is it possible to disable scrolling? To constraint screen content movement only to buttons -previous/Next or something similar.

Best regards

**Comment by ernestoyaquello** [comment]
I am not sure what your issue is. Do the steps get closed automatically when you scroll? Maybe a GIF showing your problem in action would help. Thanks!

**Comment by ernestoyaquello** [comment]
Given there hasn't been any activity in more than a month, I will close the issue.
