### ISSUE TITLE
Add and remove steps dynamically

### ISSUE THREAD

**Issue by AhmedOThman1** [ernestoyaquello/VerticalStepperForm#94]
thanks for this lib ,i want to replace continue button with a " add button and remove button" ,when clicking on the add button it's adds a new step with a specific design and when clicking on the remove button it's remove the current step .
so is it possible to **add new step or remove step programmatically** ?

**Comment by ernestoyaquello** [comment]
Hi, and sorry for the delay, I completely forgot about this issue.

The ability to do this has been added to the library (version 2.3.0). You can now add and remove steps using the methods `addStep(index, step)` and `removeStep(index)`. But please take into account that the changes will be lost on restoration (e.g., after a rotation), so you will need to save them and restore them yourself **after** the standard restoration of the form has finished.

I hope this helps, and thanks for the suggestion!
