### ISSUE TITLE
Update step number background color

### ISSUE THREAD

**Issue by kk99999** [ernestoyaquello/VerticalStepperForm#97]
Is it possible to update the step number background to any color? Like if step is success make it green else red.

**Comment by abdlhay** [comment]
if you already added it
can you help me please

**Comment by ernestoyaquello** [comment]
Hi, and sorry for the delay.

I have implemented this, you can find the new functionality in the version 2.4.0 of the library.

To use it in XML:

```xml
<ernestoyaquello.com.verticalstepperform.VerticalStepperFormView 
    ...
    app:form_circle_background_color="@color/stepNumberBackgroundColor"
    app:form_circle_completed_background_color="@color/stepNumberBackgroundColorForCompletedSteps"
    app:form_circle_error_background_color="@color/stepNumberBackgroundColorForErrorSteps"/>
```

To use it in code:

```java
verticalStepperForm
    .setup(this, userNameStep, userEmailStep, userAgeStep)
    ...
    .stepNumberColors(stepNumberBackgroundColor, stepNumberTextColor)
    .stepNumberCompletedBackgroundColor(stepNumberBackgroundColorForCompletedSteps)
    .stepNumberErrorBackgroundColor(stepNumberBackgroundColorForErrorSteps)
    ...
    .init();
```

If this implementation still doesn't suit your needs, I suggest you try to find the views you want to change and set their colours manually.

I hope this helps, and thank you for your suggestion!
